### PR TITLE
Documentation update #1

### PR DESCRIPTION
**Pull request by Dhruva-Storz**
Brought quickstart back into latest documentation, added placeholder for tutorials, and implemented basic doxygen-sphinx integration.

### CODE REVIEW

**Comment by dilawar** [comment]
Add yourself in 'author' field of pages you wrote. Make is visible.

Also add yourself to credit list.

**Comment by dilawar** [comment]
Add yourself in 'author' field of pages you wrote. Make is visible.

Also add yourself to credit list.

**Comment by hrani** [comment]
Teaching tutorial what you showed in your computer doesn't exist here, may be you forgot to commit

**Comment by hrani** [comment]
works fine

**Pull request merged**
