### PR TITLE
Calcium hsolve

### PR DESCRIPTION
**Pull request by asiaszmek**
Add communication between external calcium objects (such as DifShells) and hsolve. Add calculation and sending out current values to HSolveActive.cpp and HSolveActiveSetup.cpp. Add externalCalcium_ vector to hsolve and a function that receives concentration to and passes it to externalCalcium. advanceChannels uses externalCalcium, if Zpower>0 and there are no caConc objects in hsolve.

### CODE REVIEW

**Comment by dilawar** [comment]
@asiaszmek Is it possible to add a python test script as well? You can upload it on this thread, I'll add it to build system.

**Comment by asiaszmek** [comment]
I'll try to think of something and add it.

JJS

**Comment by dilawar** [comment]
Thanks for contribution. It looks good. Last thing I need to check if results of simulation of large model is same with these changes (fig 6 and 7, https://elifesciences.org/articles/25827/figures ). Once I confirmed that, I'll merge the PR.

Thanks again.

**Comment by dilawar** [comment]
- [ ] Fig 5
- [ ] Fig 6

**Comment by dilawar** [comment]
@asiaszmek We have removed the legacy `Makefile` based build flow. `cmake` base flow is used now. ( https://github.com/BhallaLab/moose-core/issues/180 ).

All tests have passed and this PR can be merge as soon as the above conflict is resolved.

**Comment by dilawar** [comment]
Able to merge by myself. Thanks again for contribution.

**Comment by dilawar** [comment]
I am getting the following result from your test script.

```test 14
    Start 14: pymoose-test-calcium-hsolve

14: Test command: /usr/bin/python "/home1/dilawars/SVN/GITHUB/BhallaLab/moose-core/tests/python/test_hsolve_externalCalcium.py"
14: Environment variables: 
14:  PYTHONPATH=/home1/dilawars/SVN/GITHUB/BhallaLab/moose-core/_build/python
14: Test timeout computed to be: 9.99988e+06
14: Using moose from /home1/dilawars/SVN/GITHUB/BhallaLab/moose-core/_build/python/moose/__init__.pyc
14: ReadCell: 1 compartments, 0 channels, 0 others
14: [  0.00000000e+00   1.95562717e-20   2.42687243e-20 ...,   8.03080943e-19
14:    8.03080943e-19   8.03080943e-19]
14: [  5.00000000e-05   5.00000000e-05   5.00000000e-05 ...,   5.00000000e-05
14:    5.00000000e-05   5.00000000e-05]
14: (11, 0)
````

The arrays are `sktab.vector` and `shelltab.vector`. Is that correct?
The last line containing tuple `(11,0)` is output of    

```
print(len(np.where(sktab.vector<1e-19)[0]),  len(np.where(shelltab.vector>50e-6)[0])    
````
Is that OK?

**Comment by dilawar** [comment]
There is an assertion failure when we run the test in debug mode.

````
      Start 14: pymoose-test-calcium-hsolve

14/14 Test #14: pymoose-test-calcium-hsolve ........***Exception: Other  0.88 sec

No CPU information available. Assuming single core.

No CPU information available. Assuming single core.

on node 0, numNodes = 1, numCores = 1

[INFO] Time to define moose classes:0.009991

[INFO] Time to initialize module:0.029557

Using moose from /home/travis/build/BhallaLab/moose-core/_GSL_BUILD/python/moose/__init__.pyc

ReadCell: 1 compartments, 0 channels, 0 others

python2: /home/travis/build/BhallaLab/moose-core/hsolve/HSolveInterface.cpp:249: void HSolve::addConc(Id, double): Assertion `index + 1 < externalCalcium_.size()' failed.
```

**Comment by asiaszmek** [comment]
Yes. This scipt implements a single compartment model with two channels -- one is calcium dependent and one is calcium permeable. The script tests if calcium influx via the calcium permeable channel results in a calcium increase in the difshell if the zgate is connected to calcium source and not a voltage source. In hsolve mode if there is no calcium object, zgate uses voltage information and current via the channel is much different.

**Pull request merged**
