### PR TITLE
Update rmoogli.py

### PR DESCRIPTION
**Pull request by iampritishpatil**
Fix error element not found for some valid swc files which have multisegment soma. Now it doesn't takes the first element of all those elements in the model labeled soma.

### CODE REVIEW

**Comment by dilawar** [comment]
too many files are touched by this PR. Can you send a patch or resolve the merge conflict first?

**Comment by iampritishpatil** [comment]
I actually changed only the rmoogli.py file. All the other changes aren't
files I changed, idk why they are in the pull request. I am not sure how to
change this, but its actually a single line change rmoogli.py that I made
which is in the commit de628cb4925572a48166179a5520f0aae04388c0 .

**Comment by dilawar** [comment]
All right. So I am going to cherry-pick the changes from rmoogli.py and discard the rest.

**Comment by dilawar** [comment]
`rmoogli.py` is same in this PR as well in this repo. Nothing to commit.

**Pull request closed without merging**
